// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker.proto

package org.tensorflow.distruntime;

/**
 * Protobuf type {@code tensorflow.RunGraphResponse}
 */
public final class RunGraphResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.RunGraphResponse)
    RunGraphResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RunGraphResponse.newBuilder() to construct.
  private RunGraphResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RunGraphResponse() {
    recv_ = java.util.Collections.emptyList();
    partitionGraph_ = java.util.Collections.emptyList();
    statusCode_ = 0;
    statusErrorMessage_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RunGraphResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_RunGraphResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_RunGraphResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.distruntime.RunGraphResponse.class, org.tensorflow.distruntime.RunGraphResponse.Builder.class);
  }

  public static final int RECV_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.tensorflow.framework.NamedTensorProto> recv_;
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.tensorflow.framework.NamedTensorProto> getRecvList() {
    return recv_;
  }
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.tensorflow.framework.NamedTensorProtoOrBuilder> 
      getRecvOrBuilderList() {
    return recv_;
  }
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  @java.lang.Override
  public int getRecvCount() {
    return recv_.size();
  }
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  @java.lang.Override
  public org.tensorflow.framework.NamedTensorProto getRecv(int index) {
    return recv_.get(index);
  }
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  @java.lang.Override
  public org.tensorflow.framework.NamedTensorProtoOrBuilder getRecvOrBuilder(
      int index) {
    return recv_.get(index);
  }

  public static final int STEP_STATS_FIELD_NUMBER = 2;
  private org.tensorflow.framework.StepStats stepStats_;
  /**
   * <pre>
   * If the request asked for execution stats, the cost graph, or the partition
   * graphs, these are returned here.
   * TODO(suharshs): Package these in a RunMetadata instead.
   * </pre>
   *
   * <code>.tensorflow.StepStats step_stats = 2;</code>
   * @return Whether the stepStats field is set.
   */
  @java.lang.Override
  public boolean hasStepStats() {
    return stepStats_ != null;
  }
  /**
   * <pre>
   * If the request asked for execution stats, the cost graph, or the partition
   * graphs, these are returned here.
   * TODO(suharshs): Package these in a RunMetadata instead.
   * </pre>
   *
   * <code>.tensorflow.StepStats step_stats = 2;</code>
   * @return The stepStats.
   */
  @java.lang.Override
  public org.tensorflow.framework.StepStats getStepStats() {
    return stepStats_ == null ? org.tensorflow.framework.StepStats.getDefaultInstance() : stepStats_;
  }
  /**
   * <pre>
   * If the request asked for execution stats, the cost graph, or the partition
   * graphs, these are returned here.
   * TODO(suharshs): Package these in a RunMetadata instead.
   * </pre>
   *
   * <code>.tensorflow.StepStats step_stats = 2;</code>
   */
  @java.lang.Override
  public org.tensorflow.framework.StepStatsOrBuilder getStepStatsOrBuilder() {
    return stepStats_ == null ? org.tensorflow.framework.StepStats.getDefaultInstance() : stepStats_;
  }

  public static final int COST_GRAPH_FIELD_NUMBER = 3;
  private org.tensorflow.framework.CostGraphDef costGraph_;
  /**
   * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
   * @return Whether the costGraph field is set.
   */
  @java.lang.Override
  public boolean hasCostGraph() {
    return costGraph_ != null;
  }
  /**
   * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
   * @return The costGraph.
   */
  @java.lang.Override
  public org.tensorflow.framework.CostGraphDef getCostGraph() {
    return costGraph_ == null ? org.tensorflow.framework.CostGraphDef.getDefaultInstance() : costGraph_;
  }
  /**
   * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
   */
  @java.lang.Override
  public org.tensorflow.framework.CostGraphDefOrBuilder getCostGraphOrBuilder() {
    return costGraph_ == null ? org.tensorflow.framework.CostGraphDef.getDefaultInstance() : costGraph_;
  }

  public static final int PARTITION_GRAPH_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<org.tensorflow.framework.GraphDef> partitionGraph_;
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  @java.lang.Override
  public java.util.List<org.tensorflow.framework.GraphDef> getPartitionGraphList() {
    return partitionGraph_;
  }
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.tensorflow.framework.GraphDefOrBuilder> 
      getPartitionGraphOrBuilderList() {
    return partitionGraph_;
  }
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  @java.lang.Override
  public int getPartitionGraphCount() {
    return partitionGraph_.size();
  }
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  @java.lang.Override
  public org.tensorflow.framework.GraphDef getPartitionGraph(int index) {
    return partitionGraph_.get(index);
  }
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  @java.lang.Override
  public org.tensorflow.framework.GraphDefOrBuilder getPartitionGraphOrBuilder(
      int index) {
    return partitionGraph_.get(index);
  }

  public static final int STATUS_CODE_FIELD_NUMBER = 5;
  private int statusCode_ = 0;
  /**
   * <pre>
   * If store_errors_in_response_body is true in the request, then
   * optionally the server may return an OK status for the RPC and
   * fill the true status into the fields below, to allow for messages
   * that are too long to fit in metadata.
   * </pre>
   *
   * <code>.tensorflow.error.Code status_code = 5;</code>
   * @return The enum numeric value on the wire for statusCode.
   */
  @java.lang.Override public int getStatusCodeValue() {
    return statusCode_;
  }
  /**
   * <pre>
   * If store_errors_in_response_body is true in the request, then
   * optionally the server may return an OK status for the RPC and
   * fill the true status into the fields below, to allow for messages
   * that are too long to fit in metadata.
   * </pre>
   *
   * <code>.tensorflow.error.Code status_code = 5;</code>
   * @return The statusCode.
   */
  @java.lang.Override public org.tensorflow.framework.Code getStatusCode() {
    org.tensorflow.framework.Code result = org.tensorflow.framework.Code.forNumber(statusCode_);
    return result == null ? org.tensorflow.framework.Code.UNRECOGNIZED : result;
  }

  public static final int STATUS_ERROR_MESSAGE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object statusErrorMessage_ = "";
  /**
   * <code>string status_error_message = 6;</code>
   * @return The statusErrorMessage.
   */
  @java.lang.Override
  public java.lang.String getStatusErrorMessage() {
    java.lang.Object ref = statusErrorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      statusErrorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string status_error_message = 6;</code>
   * @return The bytes for statusErrorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusErrorMessageBytes() {
    java.lang.Object ref = statusErrorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      statusErrorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < recv_.size(); i++) {
      output.writeMessage(1, recv_.get(i));
    }
    if (stepStats_ != null) {
      output.writeMessage(2, getStepStats());
    }
    if (costGraph_ != null) {
      output.writeMessage(3, getCostGraph());
    }
    for (int i = 0; i < partitionGraph_.size(); i++) {
      output.writeMessage(4, partitionGraph_.get(i));
    }
    if (statusCode_ != org.tensorflow.framework.Code.OK.getNumber()) {
      output.writeEnum(5, statusCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(statusErrorMessage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, statusErrorMessage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < recv_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, recv_.get(i));
    }
    if (stepStats_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStepStats());
    }
    if (costGraph_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCostGraph());
    }
    for (int i = 0; i < partitionGraph_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, partitionGraph_.get(i));
    }
    if (statusCode_ != org.tensorflow.framework.Code.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, statusCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(statusErrorMessage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, statusErrorMessage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tensorflow.distruntime.RunGraphResponse)) {
      return super.equals(obj);
    }
    org.tensorflow.distruntime.RunGraphResponse other = (org.tensorflow.distruntime.RunGraphResponse) obj;

    if (!getRecvList()
        .equals(other.getRecvList())) return false;
    if (hasStepStats() != other.hasStepStats()) return false;
    if (hasStepStats()) {
      if (!getStepStats()
          .equals(other.getStepStats())) return false;
    }
    if (hasCostGraph() != other.hasCostGraph()) return false;
    if (hasCostGraph()) {
      if (!getCostGraph()
          .equals(other.getCostGraph())) return false;
    }
    if (!getPartitionGraphList()
        .equals(other.getPartitionGraphList())) return false;
    if (statusCode_ != other.statusCode_) return false;
    if (!getStatusErrorMessage()
        .equals(other.getStatusErrorMessage())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRecvCount() > 0) {
      hash = (37 * hash) + RECV_FIELD_NUMBER;
      hash = (53 * hash) + getRecvList().hashCode();
    }
    if (hasStepStats()) {
      hash = (37 * hash) + STEP_STATS_FIELD_NUMBER;
      hash = (53 * hash) + getStepStats().hashCode();
    }
    if (hasCostGraph()) {
      hash = (37 * hash) + COST_GRAPH_FIELD_NUMBER;
      hash = (53 * hash) + getCostGraph().hashCode();
    }
    if (getPartitionGraphCount() > 0) {
      hash = (37 * hash) + PARTITION_GRAPH_FIELD_NUMBER;
      hash = (53 * hash) + getPartitionGraphList().hashCode();
    }
    hash = (37 * hash) + STATUS_CODE_FIELD_NUMBER;
    hash = (53 * hash) + statusCode_;
    hash = (37 * hash) + STATUS_ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getStatusErrorMessage().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tensorflow.distruntime.RunGraphResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.RunGraphResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RunGraphResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.RunGraphResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RunGraphResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.RunGraphResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RunGraphResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.RunGraphResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RunGraphResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.RunGraphResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RunGraphResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.RunGraphResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.distruntime.RunGraphResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.RunGraphResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.RunGraphResponse)
      org.tensorflow.distruntime.RunGraphResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_RunGraphResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_RunGraphResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.distruntime.RunGraphResponse.class, org.tensorflow.distruntime.RunGraphResponse.Builder.class);
    }

    // Construct using org.tensorflow.distruntime.RunGraphResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (recvBuilder_ == null) {
        recv_ = java.util.Collections.emptyList();
      } else {
        recv_ = null;
        recvBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      stepStats_ = null;
      if (stepStatsBuilder_ != null) {
        stepStatsBuilder_.dispose();
        stepStatsBuilder_ = null;
      }
      costGraph_ = null;
      if (costGraphBuilder_ != null) {
        costGraphBuilder_.dispose();
        costGraphBuilder_ = null;
      }
      if (partitionGraphBuilder_ == null) {
        partitionGraph_ = java.util.Collections.emptyList();
      } else {
        partitionGraph_ = null;
        partitionGraphBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      statusCode_ = 0;
      statusErrorMessage_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_RunGraphResponse_descriptor;
    }

    @java.lang.Override
    public org.tensorflow.distruntime.RunGraphResponse getDefaultInstanceForType() {
      return org.tensorflow.distruntime.RunGraphResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.tensorflow.distruntime.RunGraphResponse build() {
      org.tensorflow.distruntime.RunGraphResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.tensorflow.distruntime.RunGraphResponse buildPartial() {
      org.tensorflow.distruntime.RunGraphResponse result = new org.tensorflow.distruntime.RunGraphResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.tensorflow.distruntime.RunGraphResponse result) {
      if (recvBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          recv_ = java.util.Collections.unmodifiableList(recv_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.recv_ = recv_;
      } else {
        result.recv_ = recvBuilder_.build();
      }
      if (partitionGraphBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          partitionGraph_ = java.util.Collections.unmodifiableList(partitionGraph_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.partitionGraph_ = partitionGraph_;
      } else {
        result.partitionGraph_ = partitionGraphBuilder_.build();
      }
    }

    private void buildPartial0(org.tensorflow.distruntime.RunGraphResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.stepStats_ = stepStatsBuilder_ == null
            ? stepStats_
            : stepStatsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.costGraph_ = costGraphBuilder_ == null
            ? costGraph_
            : costGraphBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.statusCode_ = statusCode_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.statusErrorMessage_ = statusErrorMessage_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.distruntime.RunGraphResponse) {
        return mergeFrom((org.tensorflow.distruntime.RunGraphResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.distruntime.RunGraphResponse other) {
      if (other == org.tensorflow.distruntime.RunGraphResponse.getDefaultInstance()) return this;
      if (recvBuilder_ == null) {
        if (!other.recv_.isEmpty()) {
          if (recv_.isEmpty()) {
            recv_ = other.recv_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRecvIsMutable();
            recv_.addAll(other.recv_);
          }
          onChanged();
        }
      } else {
        if (!other.recv_.isEmpty()) {
          if (recvBuilder_.isEmpty()) {
            recvBuilder_.dispose();
            recvBuilder_ = null;
            recv_ = other.recv_;
            bitField0_ = (bitField0_ & ~0x00000001);
            recvBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRecvFieldBuilder() : null;
          } else {
            recvBuilder_.addAllMessages(other.recv_);
          }
        }
      }
      if (other.hasStepStats()) {
        mergeStepStats(other.getStepStats());
      }
      if (other.hasCostGraph()) {
        mergeCostGraph(other.getCostGraph());
      }
      if (partitionGraphBuilder_ == null) {
        if (!other.partitionGraph_.isEmpty()) {
          if (partitionGraph_.isEmpty()) {
            partitionGraph_ = other.partitionGraph_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePartitionGraphIsMutable();
            partitionGraph_.addAll(other.partitionGraph_);
          }
          onChanged();
        }
      } else {
        if (!other.partitionGraph_.isEmpty()) {
          if (partitionGraphBuilder_.isEmpty()) {
            partitionGraphBuilder_.dispose();
            partitionGraphBuilder_ = null;
            partitionGraph_ = other.partitionGraph_;
            bitField0_ = (bitField0_ & ~0x00000008);
            partitionGraphBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPartitionGraphFieldBuilder() : null;
          } else {
            partitionGraphBuilder_.addAllMessages(other.partitionGraph_);
          }
        }
      }
      if (other.statusCode_ != 0) {
        setStatusCodeValue(other.getStatusCodeValue());
      }
      if (!other.getStatusErrorMessage().isEmpty()) {
        statusErrorMessage_ = other.statusErrorMessage_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.tensorflow.framework.NamedTensorProto m =
                  input.readMessage(
                      org.tensorflow.framework.NamedTensorProto.parser(),
                      extensionRegistry);
              if (recvBuilder_ == null) {
                ensureRecvIsMutable();
                recv_.add(m);
              } else {
                recvBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getStepStatsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getCostGraphFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              org.tensorflow.framework.GraphDef m =
                  input.readMessage(
                      org.tensorflow.framework.GraphDef.parser(),
                      extensionRegistry);
              if (partitionGraphBuilder_ == null) {
                ensurePartitionGraphIsMutable();
                partitionGraph_.add(m);
              } else {
                partitionGraphBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 40: {
              statusCode_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              statusErrorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.tensorflow.framework.NamedTensorProto> recv_ =
      java.util.Collections.emptyList();
    private void ensureRecvIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        recv_ = new java.util.ArrayList<org.tensorflow.framework.NamedTensorProto>(recv_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tensorflow.framework.NamedTensorProto, org.tensorflow.framework.NamedTensorProto.Builder, org.tensorflow.framework.NamedTensorProtoOrBuilder> recvBuilder_;

    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public java.util.List<org.tensorflow.framework.NamedTensorProto> getRecvList() {
      if (recvBuilder_ == null) {
        return java.util.Collections.unmodifiableList(recv_);
      } else {
        return recvBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public int getRecvCount() {
      if (recvBuilder_ == null) {
        return recv_.size();
      } else {
        return recvBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public org.tensorflow.framework.NamedTensorProto getRecv(int index) {
      if (recvBuilder_ == null) {
        return recv_.get(index);
      } else {
        return recvBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public Builder setRecv(
        int index, org.tensorflow.framework.NamedTensorProto value) {
      if (recvBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecvIsMutable();
        recv_.set(index, value);
        onChanged();
      } else {
        recvBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public Builder setRecv(
        int index, org.tensorflow.framework.NamedTensorProto.Builder builderForValue) {
      if (recvBuilder_ == null) {
        ensureRecvIsMutable();
        recv_.set(index, builderForValue.build());
        onChanged();
      } else {
        recvBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public Builder addRecv(org.tensorflow.framework.NamedTensorProto value) {
      if (recvBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecvIsMutable();
        recv_.add(value);
        onChanged();
      } else {
        recvBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public Builder addRecv(
        int index, org.tensorflow.framework.NamedTensorProto value) {
      if (recvBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecvIsMutable();
        recv_.add(index, value);
        onChanged();
      } else {
        recvBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public Builder addRecv(
        org.tensorflow.framework.NamedTensorProto.Builder builderForValue) {
      if (recvBuilder_ == null) {
        ensureRecvIsMutable();
        recv_.add(builderForValue.build());
        onChanged();
      } else {
        recvBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public Builder addRecv(
        int index, org.tensorflow.framework.NamedTensorProto.Builder builderForValue) {
      if (recvBuilder_ == null) {
        ensureRecvIsMutable();
        recv_.add(index, builderForValue.build());
        onChanged();
      } else {
        recvBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public Builder addAllRecv(
        java.lang.Iterable<? extends org.tensorflow.framework.NamedTensorProto> values) {
      if (recvBuilder_ == null) {
        ensureRecvIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recv_);
        onChanged();
      } else {
        recvBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public Builder clearRecv() {
      if (recvBuilder_ == null) {
        recv_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        recvBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public Builder removeRecv(int index) {
      if (recvBuilder_ == null) {
        ensureRecvIsMutable();
        recv_.remove(index);
        onChanged();
      } else {
        recvBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public org.tensorflow.framework.NamedTensorProto.Builder getRecvBuilder(
        int index) {
      return getRecvFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public org.tensorflow.framework.NamedTensorProtoOrBuilder getRecvOrBuilder(
        int index) {
      if (recvBuilder_ == null) {
        return recv_.get(index);  } else {
        return recvBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public java.util.List<? extends org.tensorflow.framework.NamedTensorProtoOrBuilder> 
         getRecvOrBuilderList() {
      if (recvBuilder_ != null) {
        return recvBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(recv_);
      }
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public org.tensorflow.framework.NamedTensorProto.Builder addRecvBuilder() {
      return getRecvFieldBuilder().addBuilder(
          org.tensorflow.framework.NamedTensorProto.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public org.tensorflow.framework.NamedTensorProto.Builder addRecvBuilder(
        int index) {
      return getRecvFieldBuilder().addBuilder(
          index, org.tensorflow.framework.NamedTensorProto.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of tensors corresponding to those requested by
     * `RunGraphRequest.recv_key`.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
     */
    public java.util.List<org.tensorflow.framework.NamedTensorProto.Builder> 
         getRecvBuilderList() {
      return getRecvFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tensorflow.framework.NamedTensorProto, org.tensorflow.framework.NamedTensorProto.Builder, org.tensorflow.framework.NamedTensorProtoOrBuilder> 
        getRecvFieldBuilder() {
      if (recvBuilder_ == null) {
        recvBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.tensorflow.framework.NamedTensorProto, org.tensorflow.framework.NamedTensorProto.Builder, org.tensorflow.framework.NamedTensorProtoOrBuilder>(
                recv_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        recv_ = null;
      }
      return recvBuilder_;
    }

    private org.tensorflow.framework.StepStats stepStats_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tensorflow.framework.StepStats, org.tensorflow.framework.StepStats.Builder, org.tensorflow.framework.StepStatsOrBuilder> stepStatsBuilder_;
    /**
     * <pre>
     * If the request asked for execution stats, the cost graph, or the partition
     * graphs, these are returned here.
     * TODO(suharshs): Package these in a RunMetadata instead.
     * </pre>
     *
     * <code>.tensorflow.StepStats step_stats = 2;</code>
     * @return Whether the stepStats field is set.
     */
    public boolean hasStepStats() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * If the request asked for execution stats, the cost graph, or the partition
     * graphs, these are returned here.
     * TODO(suharshs): Package these in a RunMetadata instead.
     * </pre>
     *
     * <code>.tensorflow.StepStats step_stats = 2;</code>
     * @return The stepStats.
     */
    public org.tensorflow.framework.StepStats getStepStats() {
      if (stepStatsBuilder_ == null) {
        return stepStats_ == null ? org.tensorflow.framework.StepStats.getDefaultInstance() : stepStats_;
      } else {
        return stepStatsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * If the request asked for execution stats, the cost graph, or the partition
     * graphs, these are returned here.
     * TODO(suharshs): Package these in a RunMetadata instead.
     * </pre>
     *
     * <code>.tensorflow.StepStats step_stats = 2;</code>
     */
    public Builder setStepStats(org.tensorflow.framework.StepStats value) {
      if (stepStatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stepStats_ = value;
      } else {
        stepStatsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If the request asked for execution stats, the cost graph, or the partition
     * graphs, these are returned here.
     * TODO(suharshs): Package these in a RunMetadata instead.
     * </pre>
     *
     * <code>.tensorflow.StepStats step_stats = 2;</code>
     */
    public Builder setStepStats(
        org.tensorflow.framework.StepStats.Builder builderForValue) {
      if (stepStatsBuilder_ == null) {
        stepStats_ = builderForValue.build();
      } else {
        stepStatsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If the request asked for execution stats, the cost graph, or the partition
     * graphs, these are returned here.
     * TODO(suharshs): Package these in a RunMetadata instead.
     * </pre>
     *
     * <code>.tensorflow.StepStats step_stats = 2;</code>
     */
    public Builder mergeStepStats(org.tensorflow.framework.StepStats value) {
      if (stepStatsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          stepStats_ != null &&
          stepStats_ != org.tensorflow.framework.StepStats.getDefaultInstance()) {
          getStepStatsBuilder().mergeFrom(value);
        } else {
          stepStats_ = value;
        }
      } else {
        stepStatsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If the request asked for execution stats, the cost graph, or the partition
     * graphs, these are returned here.
     * TODO(suharshs): Package these in a RunMetadata instead.
     * </pre>
     *
     * <code>.tensorflow.StepStats step_stats = 2;</code>
     */
    public Builder clearStepStats() {
      bitField0_ = (bitField0_ & ~0x00000002);
      stepStats_ = null;
      if (stepStatsBuilder_ != null) {
        stepStatsBuilder_.dispose();
        stepStatsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If the request asked for execution stats, the cost graph, or the partition
     * graphs, these are returned here.
     * TODO(suharshs): Package these in a RunMetadata instead.
     * </pre>
     *
     * <code>.tensorflow.StepStats step_stats = 2;</code>
     */
    public org.tensorflow.framework.StepStats.Builder getStepStatsBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getStepStatsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * If the request asked for execution stats, the cost graph, or the partition
     * graphs, these are returned here.
     * TODO(suharshs): Package these in a RunMetadata instead.
     * </pre>
     *
     * <code>.tensorflow.StepStats step_stats = 2;</code>
     */
    public org.tensorflow.framework.StepStatsOrBuilder getStepStatsOrBuilder() {
      if (stepStatsBuilder_ != null) {
        return stepStatsBuilder_.getMessageOrBuilder();
      } else {
        return stepStats_ == null ?
            org.tensorflow.framework.StepStats.getDefaultInstance() : stepStats_;
      }
    }
    /**
     * <pre>
     * If the request asked for execution stats, the cost graph, or the partition
     * graphs, these are returned here.
     * TODO(suharshs): Package these in a RunMetadata instead.
     * </pre>
     *
     * <code>.tensorflow.StepStats step_stats = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tensorflow.framework.StepStats, org.tensorflow.framework.StepStats.Builder, org.tensorflow.framework.StepStatsOrBuilder> 
        getStepStatsFieldBuilder() {
      if (stepStatsBuilder_ == null) {
        stepStatsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.tensorflow.framework.StepStats, org.tensorflow.framework.StepStats.Builder, org.tensorflow.framework.StepStatsOrBuilder>(
                getStepStats(),
                getParentForChildren(),
                isClean());
        stepStats_ = null;
      }
      return stepStatsBuilder_;
    }

    private org.tensorflow.framework.CostGraphDef costGraph_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tensorflow.framework.CostGraphDef, org.tensorflow.framework.CostGraphDef.Builder, org.tensorflow.framework.CostGraphDefOrBuilder> costGraphBuilder_;
    /**
     * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
     * @return Whether the costGraph field is set.
     */
    public boolean hasCostGraph() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
     * @return The costGraph.
     */
    public org.tensorflow.framework.CostGraphDef getCostGraph() {
      if (costGraphBuilder_ == null) {
        return costGraph_ == null ? org.tensorflow.framework.CostGraphDef.getDefaultInstance() : costGraph_;
      } else {
        return costGraphBuilder_.getMessage();
      }
    }
    /**
     * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
     */
    public Builder setCostGraph(org.tensorflow.framework.CostGraphDef value) {
      if (costGraphBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        costGraph_ = value;
      } else {
        costGraphBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
     */
    public Builder setCostGraph(
        org.tensorflow.framework.CostGraphDef.Builder builderForValue) {
      if (costGraphBuilder_ == null) {
        costGraph_ = builderForValue.build();
      } else {
        costGraphBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
     */
    public Builder mergeCostGraph(org.tensorflow.framework.CostGraphDef value) {
      if (costGraphBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          costGraph_ != null &&
          costGraph_ != org.tensorflow.framework.CostGraphDef.getDefaultInstance()) {
          getCostGraphBuilder().mergeFrom(value);
        } else {
          costGraph_ = value;
        }
      } else {
        costGraphBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
     */
    public Builder clearCostGraph() {
      bitField0_ = (bitField0_ & ~0x00000004);
      costGraph_ = null;
      if (costGraphBuilder_ != null) {
        costGraphBuilder_.dispose();
        costGraphBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
     */
    public org.tensorflow.framework.CostGraphDef.Builder getCostGraphBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getCostGraphFieldBuilder().getBuilder();
    }
    /**
     * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
     */
    public org.tensorflow.framework.CostGraphDefOrBuilder getCostGraphOrBuilder() {
      if (costGraphBuilder_ != null) {
        return costGraphBuilder_.getMessageOrBuilder();
      } else {
        return costGraph_ == null ?
            org.tensorflow.framework.CostGraphDef.getDefaultInstance() : costGraph_;
      }
    }
    /**
     * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tensorflow.framework.CostGraphDef, org.tensorflow.framework.CostGraphDef.Builder, org.tensorflow.framework.CostGraphDefOrBuilder> 
        getCostGraphFieldBuilder() {
      if (costGraphBuilder_ == null) {
        costGraphBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.tensorflow.framework.CostGraphDef, org.tensorflow.framework.CostGraphDef.Builder, org.tensorflow.framework.CostGraphDefOrBuilder>(
                getCostGraph(),
                getParentForChildren(),
                isClean());
        costGraph_ = null;
      }
      return costGraphBuilder_;
    }

    private java.util.List<org.tensorflow.framework.GraphDef> partitionGraph_ =
      java.util.Collections.emptyList();
    private void ensurePartitionGraphIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        partitionGraph_ = new java.util.ArrayList<org.tensorflow.framework.GraphDef>(partitionGraph_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tensorflow.framework.GraphDef, org.tensorflow.framework.GraphDef.Builder, org.tensorflow.framework.GraphDefOrBuilder> partitionGraphBuilder_;

    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public java.util.List<org.tensorflow.framework.GraphDef> getPartitionGraphList() {
      if (partitionGraphBuilder_ == null) {
        return java.util.Collections.unmodifiableList(partitionGraph_);
      } else {
        return partitionGraphBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public int getPartitionGraphCount() {
      if (partitionGraphBuilder_ == null) {
        return partitionGraph_.size();
      } else {
        return partitionGraphBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public org.tensorflow.framework.GraphDef getPartitionGraph(int index) {
      if (partitionGraphBuilder_ == null) {
        return partitionGraph_.get(index);
      } else {
        return partitionGraphBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public Builder setPartitionGraph(
        int index, org.tensorflow.framework.GraphDef value) {
      if (partitionGraphBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionGraphIsMutable();
        partitionGraph_.set(index, value);
        onChanged();
      } else {
        partitionGraphBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public Builder setPartitionGraph(
        int index, org.tensorflow.framework.GraphDef.Builder builderForValue) {
      if (partitionGraphBuilder_ == null) {
        ensurePartitionGraphIsMutable();
        partitionGraph_.set(index, builderForValue.build());
        onChanged();
      } else {
        partitionGraphBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public Builder addPartitionGraph(org.tensorflow.framework.GraphDef value) {
      if (partitionGraphBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionGraphIsMutable();
        partitionGraph_.add(value);
        onChanged();
      } else {
        partitionGraphBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public Builder addPartitionGraph(
        int index, org.tensorflow.framework.GraphDef value) {
      if (partitionGraphBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionGraphIsMutable();
        partitionGraph_.add(index, value);
        onChanged();
      } else {
        partitionGraphBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public Builder addPartitionGraph(
        org.tensorflow.framework.GraphDef.Builder builderForValue) {
      if (partitionGraphBuilder_ == null) {
        ensurePartitionGraphIsMutable();
        partitionGraph_.add(builderForValue.build());
        onChanged();
      } else {
        partitionGraphBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public Builder addPartitionGraph(
        int index, org.tensorflow.framework.GraphDef.Builder builderForValue) {
      if (partitionGraphBuilder_ == null) {
        ensurePartitionGraphIsMutable();
        partitionGraph_.add(index, builderForValue.build());
        onChanged();
      } else {
        partitionGraphBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public Builder addAllPartitionGraph(
        java.lang.Iterable<? extends org.tensorflow.framework.GraphDef> values) {
      if (partitionGraphBuilder_ == null) {
        ensurePartitionGraphIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, partitionGraph_);
        onChanged();
      } else {
        partitionGraphBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public Builder clearPartitionGraph() {
      if (partitionGraphBuilder_ == null) {
        partitionGraph_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        partitionGraphBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public Builder removePartitionGraph(int index) {
      if (partitionGraphBuilder_ == null) {
        ensurePartitionGraphIsMutable();
        partitionGraph_.remove(index);
        onChanged();
      } else {
        partitionGraphBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public org.tensorflow.framework.GraphDef.Builder getPartitionGraphBuilder(
        int index) {
      return getPartitionGraphFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public org.tensorflow.framework.GraphDefOrBuilder getPartitionGraphOrBuilder(
        int index) {
      if (partitionGraphBuilder_ == null) {
        return partitionGraph_.get(index);  } else {
        return partitionGraphBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public java.util.List<? extends org.tensorflow.framework.GraphDefOrBuilder> 
         getPartitionGraphOrBuilderList() {
      if (partitionGraphBuilder_ != null) {
        return partitionGraphBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(partitionGraph_);
      }
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public org.tensorflow.framework.GraphDef.Builder addPartitionGraphBuilder() {
      return getPartitionGraphFieldBuilder().addBuilder(
          org.tensorflow.framework.GraphDef.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public org.tensorflow.framework.GraphDef.Builder addPartitionGraphBuilder(
        int index) {
      return getPartitionGraphFieldBuilder().addBuilder(
          index, org.tensorflow.framework.GraphDef.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
     */
    public java.util.List<org.tensorflow.framework.GraphDef.Builder> 
         getPartitionGraphBuilderList() {
      return getPartitionGraphFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tensorflow.framework.GraphDef, org.tensorflow.framework.GraphDef.Builder, org.tensorflow.framework.GraphDefOrBuilder> 
        getPartitionGraphFieldBuilder() {
      if (partitionGraphBuilder_ == null) {
        partitionGraphBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.tensorflow.framework.GraphDef, org.tensorflow.framework.GraphDef.Builder, org.tensorflow.framework.GraphDefOrBuilder>(
                partitionGraph_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        partitionGraph_ = null;
      }
      return partitionGraphBuilder_;
    }

    private int statusCode_ = 0;
    /**
     * <pre>
     * If store_errors_in_response_body is true in the request, then
     * optionally the server may return an OK status for the RPC and
     * fill the true status into the fields below, to allow for messages
     * that are too long to fit in metadata.
     * </pre>
     *
     * <code>.tensorflow.error.Code status_code = 5;</code>
     * @return The enum numeric value on the wire for statusCode.
     */
    @java.lang.Override public int getStatusCodeValue() {
      return statusCode_;
    }
    /**
     * <pre>
     * If store_errors_in_response_body is true in the request, then
     * optionally the server may return an OK status for the RPC and
     * fill the true status into the fields below, to allow for messages
     * that are too long to fit in metadata.
     * </pre>
     *
     * <code>.tensorflow.error.Code status_code = 5;</code>
     * @param value The enum numeric value on the wire for statusCode to set.
     * @return This builder for chaining.
     */
    public Builder setStatusCodeValue(int value) {
      statusCode_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If store_errors_in_response_body is true in the request, then
     * optionally the server may return an OK status for the RPC and
     * fill the true status into the fields below, to allow for messages
     * that are too long to fit in metadata.
     * </pre>
     *
     * <code>.tensorflow.error.Code status_code = 5;</code>
     * @return The statusCode.
     */
    @java.lang.Override
    public org.tensorflow.framework.Code getStatusCode() {
      org.tensorflow.framework.Code result = org.tensorflow.framework.Code.forNumber(statusCode_);
      return result == null ? org.tensorflow.framework.Code.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * If store_errors_in_response_body is true in the request, then
     * optionally the server may return an OK status for the RPC and
     * fill the true status into the fields below, to allow for messages
     * that are too long to fit in metadata.
     * </pre>
     *
     * <code>.tensorflow.error.Code status_code = 5;</code>
     * @param value The statusCode to set.
     * @return This builder for chaining.
     */
    public Builder setStatusCode(org.tensorflow.framework.Code value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      statusCode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If store_errors_in_response_body is true in the request, then
     * optionally the server may return an OK status for the RPC and
     * fill the true status into the fields below, to allow for messages
     * that are too long to fit in metadata.
     * </pre>
     *
     * <code>.tensorflow.error.Code status_code = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatusCode() {
      bitField0_ = (bitField0_ & ~0x00000010);
      statusCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object statusErrorMessage_ = "";
    /**
     * <code>string status_error_message = 6;</code>
     * @return The statusErrorMessage.
     */
    public java.lang.String getStatusErrorMessage() {
      java.lang.Object ref = statusErrorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statusErrorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status_error_message = 6;</code>
     * @return The bytes for statusErrorMessage.
     */
    public com.google.protobuf.ByteString
        getStatusErrorMessageBytes() {
      java.lang.Object ref = statusErrorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusErrorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status_error_message = 6;</code>
     * @param value The statusErrorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setStatusErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      statusErrorMessage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string status_error_message = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatusErrorMessage() {
      statusErrorMessage_ = getDefaultInstance().getStatusErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string status_error_message = 6;</code>
     * @param value The bytes for statusErrorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setStatusErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      statusErrorMessage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.RunGraphResponse)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.RunGraphResponse)
  private static final org.tensorflow.distruntime.RunGraphResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.distruntime.RunGraphResponse();
  }

  public static org.tensorflow.distruntime.RunGraphResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RunGraphResponse>
      PARSER = new com.google.protobuf.AbstractParser<RunGraphResponse>() {
    @java.lang.Override
    public RunGraphResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RunGraphResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RunGraphResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.tensorflow.distruntime.RunGraphResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

