// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/util/event.proto

package org.tensorflow.util;

public interface WorkerHeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.WorkerHeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tensorflow.WorkerHealth health_status = 1;</code>
   * @return The enum numeric value on the wire for healthStatus.
   */
  int getHealthStatusValue();
  /**
   * <code>.tensorflow.WorkerHealth health_status = 1;</code>
   * @return The healthStatus.
   */
  org.tensorflow.util.WorkerHealth getHealthStatus();

  /**
   * <code>repeated .tensorflow.Event worker_log = 2;</code>
   */
  java.util.List<org.tensorflow.util.Event> 
      getWorkerLogList();
  /**
   * <code>repeated .tensorflow.Event worker_log = 2;</code>
   */
  org.tensorflow.util.Event getWorkerLog(int index);
  /**
   * <code>repeated .tensorflow.Event worker_log = 2;</code>
   */
  int getWorkerLogCount();
  /**
   * <code>repeated .tensorflow.Event worker_log = 2;</code>
   */
  java.util.List<? extends org.tensorflow.util.EventOrBuilder> 
      getWorkerLogOrBuilderList();
  /**
   * <code>repeated .tensorflow.Event worker_log = 2;</code>
   */
  org.tensorflow.util.EventOrBuilder getWorkerLogOrBuilder(
      int index);

  /**
   * <code>string hostname = 3;</code>
   * @return The hostname.
   */
  java.lang.String getHostname();
  /**
   * <code>string hostname = 3;</code>
   * @return The bytes for hostname.
   */
  com.google.protobuf.ByteString
      getHostnameBytes();
}
