// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow_serving/config/monitoring_config.proto

package tensorflow.serving;

public final class MonitoringConfigOuterClass {
  private MonitoringConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PrometheusConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.PrometheusConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Whether to expose Prometheus metrics.
     * </pre>
     *
     * <code>bool enable = 1;</code>
     * @return The enable.
     */
    boolean getEnable();

    /**
     * <pre>
     * The endpoint to expose Prometheus metrics.
     * If not specified, PrometheusExporter::kPrometheusPath value is used.
     * </pre>
     *
     * <code>string path = 2;</code>
     * @return The path.
     */
    java.lang.String getPath();
    /**
     * <pre>
     * The endpoint to expose Prometheus metrics.
     * If not specified, PrometheusExporter::kPrometheusPath value is used.
     * </pre>
     *
     * <code>string path = 2;</code>
     * @return The bytes for path.
     */
    com.google.protobuf.ByteString
        getPathBytes();
  }
  /**
   * <pre>
   * Configuration for Prometheus monitoring.
   * </pre>
   *
   * Protobuf type {@code tensorflow.serving.PrometheusConfig}
   */
  public static final class PrometheusConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.PrometheusConfig)
      PrometheusConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PrometheusConfig.newBuilder() to construct.
    private PrometheusConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PrometheusConfig() {
      path_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PrometheusConfig();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tensorflow.serving.MonitoringConfigOuterClass.internal_static_tensorflow_serving_PrometheusConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tensorflow.serving.MonitoringConfigOuterClass.internal_static_tensorflow_serving_PrometheusConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.class, tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.Builder.class);
    }

    public static final int ENABLE_FIELD_NUMBER = 1;
    private boolean enable_ = false;
    /**
     * <pre>
     * Whether to expose Prometheus metrics.
     * </pre>
     *
     * <code>bool enable = 1;</code>
     * @return The enable.
     */
    @java.lang.Override
    public boolean getEnable() {
      return enable_;
    }

    public static final int PATH_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object path_ = "";
    /**
     * <pre>
     * The endpoint to expose Prometheus metrics.
     * If not specified, PrometheusExporter::kPrometheusPath value is used.
     * </pre>
     *
     * <code>string path = 2;</code>
     * @return The path.
     */
    @java.lang.Override
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The endpoint to expose Prometheus metrics.
     * If not specified, PrometheusExporter::kPrometheusPath value is used.
     * </pre>
     *
     * <code>string path = 2;</code>
     * @return The bytes for path.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (enable_ != false) {
        output.writeBool(1, enable_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, path_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (enable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, enable_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, path_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig)) {
        return super.equals(obj);
      }
      tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig other = (tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig) obj;

      if (getEnable()
          != other.getEnable()) return false;
      if (!getPath()
          .equals(other.getPath())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnable());
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration for Prometheus monitoring.
     * </pre>
     *
     * Protobuf type {@code tensorflow.serving.PrometheusConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.PrometheusConfig)
        tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tensorflow.serving.MonitoringConfigOuterClass.internal_static_tensorflow_serving_PrometheusConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tensorflow.serving.MonitoringConfigOuterClass.internal_static_tensorflow_serving_PrometheusConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.class, tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.Builder.class);
      }

      // Construct using tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        enable_ = false;
        path_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tensorflow.serving.MonitoringConfigOuterClass.internal_static_tensorflow_serving_PrometheusConfig_descriptor;
      }

      @java.lang.Override
      public tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig getDefaultInstanceForType() {
        return tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.getDefaultInstance();
      }

      @java.lang.Override
      public tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig build() {
        tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig buildPartial() {
        tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig result = new tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.enable_ = enable_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.path_ = path_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig) {
          return mergeFrom((tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig other) {
        if (other == tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.getDefaultInstance()) return this;
        if (other.getEnable() != false) {
          setEnable(other.getEnable());
        }
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                enable_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                path_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean enable_ ;
      /**
       * <pre>
       * Whether to expose Prometheus metrics.
       * </pre>
       *
       * <code>bool enable = 1;</code>
       * @return The enable.
       */
      @java.lang.Override
      public boolean getEnable() {
        return enable_;
      }
      /**
       * <pre>
       * Whether to expose Prometheus metrics.
       * </pre>
       *
       * <code>bool enable = 1;</code>
       * @param value The enable to set.
       * @return This builder for chaining.
       */
      public Builder setEnable(boolean value) {
        
        enable_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether to expose Prometheus metrics.
       * </pre>
       *
       * <code>bool enable = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnable() {
        bitField0_ = (bitField0_ & ~0x00000001);
        enable_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <pre>
       * The endpoint to expose Prometheus metrics.
       * If not specified, PrometheusExporter::kPrometheusPath value is used.
       * </pre>
       *
       * <code>string path = 2;</code>
       * @return The path.
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The endpoint to expose Prometheus metrics.
       * If not specified, PrometheusExporter::kPrometheusPath value is used.
       * </pre>
       *
       * <code>string path = 2;</code>
       * @return The bytes for path.
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The endpoint to expose Prometheus metrics.
       * If not specified, PrometheusExporter::kPrometheusPath value is used.
       * </pre>
       *
       * <code>string path = 2;</code>
       * @param value The path to set.
       * @return This builder for chaining.
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        path_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The endpoint to expose Prometheus metrics.
       * If not specified, PrometheusExporter::kPrometheusPath value is used.
       * </pre>
       *
       * <code>string path = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPath() {
        path_ = getDefaultInstance().getPath();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The endpoint to expose Prometheus metrics.
       * If not specified, PrometheusExporter::kPrometheusPath value is used.
       * </pre>
       *
       * <code>string path = 2;</code>
       * @param value The bytes for path to set.
       * @return This builder for chaining.
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        path_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.PrometheusConfig)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.PrometheusConfig)
    private static final tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig();
    }

    public static tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PrometheusConfig>
        PARSER = new com.google.protobuf.AbstractParser<PrometheusConfig>() {
      @java.lang.Override
      public PrometheusConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PrometheusConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PrometheusConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MonitoringConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.MonitoringConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
     * @return Whether the prometheusConfig field is set.
     */
    boolean hasPrometheusConfig();
    /**
     * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
     * @return The prometheusConfig.
     */
    tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig getPrometheusConfig();
    /**
     * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
     */
    tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfigOrBuilder getPrometheusConfigOrBuilder();
  }
  /**
   * <pre>
   * Configuration for monitoring.
   * </pre>
   *
   * Protobuf type {@code tensorflow.serving.MonitoringConfig}
   */
  public static final class MonitoringConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.MonitoringConfig)
      MonitoringConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MonitoringConfig.newBuilder() to construct.
    private MonitoringConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MonitoringConfig() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MonitoringConfig();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tensorflow.serving.MonitoringConfigOuterClass.internal_static_tensorflow_serving_MonitoringConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tensorflow.serving.MonitoringConfigOuterClass.internal_static_tensorflow_serving_MonitoringConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig.class, tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig.Builder.class);
    }

    public static final int PROMETHEUS_CONFIG_FIELD_NUMBER = 1;
    private tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig prometheusConfig_;
    /**
     * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
     * @return Whether the prometheusConfig field is set.
     */
    @java.lang.Override
    public boolean hasPrometheusConfig() {
      return prometheusConfig_ != null;
    }
    /**
     * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
     * @return The prometheusConfig.
     */
    @java.lang.Override
    public tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig getPrometheusConfig() {
      return prometheusConfig_ == null ? tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.getDefaultInstance() : prometheusConfig_;
    }
    /**
     * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
     */
    @java.lang.Override
    public tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfigOrBuilder getPrometheusConfigOrBuilder() {
      return prometheusConfig_ == null ? tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.getDefaultInstance() : prometheusConfig_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (prometheusConfig_ != null) {
        output.writeMessage(1, getPrometheusConfig());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (prometheusConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPrometheusConfig());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig)) {
        return super.equals(obj);
      }
      tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig other = (tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig) obj;

      if (hasPrometheusConfig() != other.hasPrometheusConfig()) return false;
      if (hasPrometheusConfig()) {
        if (!getPrometheusConfig()
            .equals(other.getPrometheusConfig())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPrometheusConfig()) {
        hash = (37 * hash) + PROMETHEUS_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getPrometheusConfig().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration for monitoring.
     * </pre>
     *
     * Protobuf type {@code tensorflow.serving.MonitoringConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.MonitoringConfig)
        tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tensorflow.serving.MonitoringConfigOuterClass.internal_static_tensorflow_serving_MonitoringConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tensorflow.serving.MonitoringConfigOuterClass.internal_static_tensorflow_serving_MonitoringConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig.class, tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig.Builder.class);
      }

      // Construct using tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        prometheusConfig_ = null;
        if (prometheusConfigBuilder_ != null) {
          prometheusConfigBuilder_.dispose();
          prometheusConfigBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tensorflow.serving.MonitoringConfigOuterClass.internal_static_tensorflow_serving_MonitoringConfig_descriptor;
      }

      @java.lang.Override
      public tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig getDefaultInstanceForType() {
        return tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig.getDefaultInstance();
      }

      @java.lang.Override
      public tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig build() {
        tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig buildPartial() {
        tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig result = new tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.prometheusConfig_ = prometheusConfigBuilder_ == null
              ? prometheusConfig_
              : prometheusConfigBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig) {
          return mergeFrom((tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig other) {
        if (other == tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig.getDefaultInstance()) return this;
        if (other.hasPrometheusConfig()) {
          mergePrometheusConfig(other.getPrometheusConfig());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getPrometheusConfigFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig prometheusConfig_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig, tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.Builder, tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfigOrBuilder> prometheusConfigBuilder_;
      /**
       * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
       * @return Whether the prometheusConfig field is set.
       */
      public boolean hasPrometheusConfig() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
       * @return The prometheusConfig.
       */
      public tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig getPrometheusConfig() {
        if (prometheusConfigBuilder_ == null) {
          return prometheusConfig_ == null ? tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.getDefaultInstance() : prometheusConfig_;
        } else {
          return prometheusConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
       */
      public Builder setPrometheusConfig(tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig value) {
        if (prometheusConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          prometheusConfig_ = value;
        } else {
          prometheusConfigBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
       */
      public Builder setPrometheusConfig(
          tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.Builder builderForValue) {
        if (prometheusConfigBuilder_ == null) {
          prometheusConfig_ = builderForValue.build();
        } else {
          prometheusConfigBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
       */
      public Builder mergePrometheusConfig(tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig value) {
        if (prometheusConfigBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            prometheusConfig_ != null &&
            prometheusConfig_ != tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.getDefaultInstance()) {
            getPrometheusConfigBuilder().mergeFrom(value);
          } else {
            prometheusConfig_ = value;
          }
        } else {
          prometheusConfigBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
       */
      public Builder clearPrometheusConfig() {
        bitField0_ = (bitField0_ & ~0x00000001);
        prometheusConfig_ = null;
        if (prometheusConfigBuilder_ != null) {
          prometheusConfigBuilder_.dispose();
          prometheusConfigBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
       */
      public tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.Builder getPrometheusConfigBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPrometheusConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
       */
      public tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfigOrBuilder getPrometheusConfigOrBuilder() {
        if (prometheusConfigBuilder_ != null) {
          return prometheusConfigBuilder_.getMessageOrBuilder();
        } else {
          return prometheusConfig_ == null ?
              tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.getDefaultInstance() : prometheusConfig_;
        }
      }
      /**
       * <code>.tensorflow.serving.PrometheusConfig prometheus_config = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig, tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.Builder, tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfigOrBuilder> 
          getPrometheusConfigFieldBuilder() {
        if (prometheusConfigBuilder_ == null) {
          prometheusConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig, tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfig.Builder, tensorflow.serving.MonitoringConfigOuterClass.PrometheusConfigOrBuilder>(
                  getPrometheusConfig(),
                  getParentForChildren(),
                  isClean());
          prometheusConfig_ = null;
        }
        return prometheusConfigBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.MonitoringConfig)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.MonitoringConfig)
    private static final tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig();
    }

    public static tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MonitoringConfig>
        PARSER = new com.google.protobuf.AbstractParser<MonitoringConfig>() {
      @java.lang.Override
      public MonitoringConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MonitoringConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MonitoringConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tensorflow.serving.MonitoringConfigOuterClass.MonitoringConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_PrometheusConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_PrometheusConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_MonitoringConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_MonitoringConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1tensorflow_serving/config/monitoring_c" +
      "onfig.proto\022\022tensorflow.serving\"0\n\020Prome" +
      "theusConfig\022\016\n\006enable\030\001 \001(\010\022\014\n\004path\030\002 \001(" +
      "\t\"S\n\020MonitoringConfig\022?\n\021prometheus_conf" +
      "ig\030\001 \001(\0132$.tensorflow.serving.Prometheus" +
      "ConfigB\003\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tensorflow_serving_PrometheusConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_serving_PrometheusConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_PrometheusConfig_descriptor,
        new java.lang.String[] { "Enable", "Path", });
    internal_static_tensorflow_serving_MonitoringConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_serving_MonitoringConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_MonitoringConfig_descriptor,
        new java.lang.String[] { "PrometheusConfig", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
