// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/example/example_parser_configuration.proto

package org.tensorflow.example;

/**
 * Protobuf type {@code tensorflow.ExampleParserConfiguration}
 */
public final class ExampleParserConfiguration extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.ExampleParserConfiguration)
    ExampleParserConfigurationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExampleParserConfiguration.newBuilder() to construct.
  private ExampleParserConfiguration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExampleParserConfiguration() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExampleParserConfiguration();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.example.ExampleParserConfigurationProtos.internal_static_tensorflow_ExampleParserConfiguration_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetFeatureMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.example.ExampleParserConfigurationProtos.internal_static_tensorflow_ExampleParserConfiguration_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.example.ExampleParserConfiguration.class, org.tensorflow.example.ExampleParserConfiguration.Builder.class);
  }

  public static final int FEATURE_MAP_FIELD_NUMBER = 1;
  private static final class FeatureMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, org.tensorflow.example.FeatureConfiguration> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, org.tensorflow.example.FeatureConfiguration>newDefaultInstance(
                org.tensorflow.example.ExampleParserConfigurationProtos.internal_static_tensorflow_ExampleParserConfiguration_FeatureMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                org.tensorflow.example.FeatureConfiguration.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, org.tensorflow.example.FeatureConfiguration> featureMap_;
  private com.google.protobuf.MapField<java.lang.String, org.tensorflow.example.FeatureConfiguration>
  internalGetFeatureMap() {
    if (featureMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FeatureMapDefaultEntryHolder.defaultEntry);
    }
    return featureMap_;
  }
  public int getFeatureMapCount() {
    return internalGetFeatureMap().getMap().size();
  }
  /**
   * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
   */
  @java.lang.Override
  public boolean containsFeatureMap(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetFeatureMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFeatureMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, org.tensorflow.example.FeatureConfiguration> getFeatureMap() {
    return getFeatureMapMap();
  }
  /**
   * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, org.tensorflow.example.FeatureConfiguration> getFeatureMapMap() {
    return internalGetFeatureMap().getMap();
  }
  /**
   * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
org.tensorflow.example.FeatureConfiguration getFeatureMapOrDefault(
      java.lang.String key,
      /* nullable */
org.tensorflow.example.FeatureConfiguration defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, org.tensorflow.example.FeatureConfiguration> map =
        internalGetFeatureMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
   */
  @java.lang.Override
  public org.tensorflow.example.FeatureConfiguration getFeatureMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, org.tensorflow.example.FeatureConfiguration> map =
        internalGetFeatureMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetFeatureMap(),
        FeatureMapDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, org.tensorflow.example.FeatureConfiguration> entry
         : internalGetFeatureMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, org.tensorflow.example.FeatureConfiguration>
      featureMap__ = FeatureMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, featureMap__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tensorflow.example.ExampleParserConfiguration)) {
      return super.equals(obj);
    }
    org.tensorflow.example.ExampleParserConfiguration other = (org.tensorflow.example.ExampleParserConfiguration) obj;

    if (!internalGetFeatureMap().equals(
        other.internalGetFeatureMap())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetFeatureMap().getMap().isEmpty()) {
      hash = (37 * hash) + FEATURE_MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFeatureMap().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tensorflow.example.ExampleParserConfiguration parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.example.ExampleParserConfiguration parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.example.ExampleParserConfiguration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.example.ExampleParserConfiguration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.example.ExampleParserConfiguration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.example.ExampleParserConfiguration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.example.ExampleParserConfiguration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.example.ExampleParserConfiguration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.example.ExampleParserConfiguration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tensorflow.example.ExampleParserConfiguration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.example.ExampleParserConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.example.ExampleParserConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.example.ExampleParserConfiguration prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.ExampleParserConfiguration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.ExampleParserConfiguration)
      org.tensorflow.example.ExampleParserConfigurationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.example.ExampleParserConfigurationProtos.internal_static_tensorflow_ExampleParserConfiguration_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetFeatureMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableFeatureMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.example.ExampleParserConfigurationProtos.internal_static_tensorflow_ExampleParserConfiguration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.example.ExampleParserConfiguration.class, org.tensorflow.example.ExampleParserConfiguration.Builder.class);
    }

    // Construct using org.tensorflow.example.ExampleParserConfiguration.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableFeatureMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.example.ExampleParserConfigurationProtos.internal_static_tensorflow_ExampleParserConfiguration_descriptor;
    }

    @java.lang.Override
    public org.tensorflow.example.ExampleParserConfiguration getDefaultInstanceForType() {
      return org.tensorflow.example.ExampleParserConfiguration.getDefaultInstance();
    }

    @java.lang.Override
    public org.tensorflow.example.ExampleParserConfiguration build() {
      org.tensorflow.example.ExampleParserConfiguration result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.tensorflow.example.ExampleParserConfiguration buildPartial() {
      org.tensorflow.example.ExampleParserConfiguration result = new org.tensorflow.example.ExampleParserConfiguration(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.tensorflow.example.ExampleParserConfiguration result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.featureMap_ = internalGetFeatureMap();
        result.featureMap_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.example.ExampleParserConfiguration) {
        return mergeFrom((org.tensorflow.example.ExampleParserConfiguration)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.example.ExampleParserConfiguration other) {
      if (other == org.tensorflow.example.ExampleParserConfiguration.getDefaultInstance()) return this;
      internalGetMutableFeatureMap().mergeFrom(
          other.internalGetFeatureMap());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, org.tensorflow.example.FeatureConfiguration>
              featureMap__ = input.readMessage(
                  FeatureMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableFeatureMap().getMutableMap().put(
                  featureMap__.getKey(), featureMap__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, org.tensorflow.example.FeatureConfiguration> featureMap_;
    private com.google.protobuf.MapField<java.lang.String, org.tensorflow.example.FeatureConfiguration>
        internalGetFeatureMap() {
      if (featureMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FeatureMapDefaultEntryHolder.defaultEntry);
      }
      return featureMap_;
    }
    private com.google.protobuf.MapField<java.lang.String, org.tensorflow.example.FeatureConfiguration>
        internalGetMutableFeatureMap() {
      if (featureMap_ == null) {
        featureMap_ = com.google.protobuf.MapField.newMapField(
            FeatureMapDefaultEntryHolder.defaultEntry);
      }
      if (!featureMap_.isMutable()) {
        featureMap_ = featureMap_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return featureMap_;
    }
    public int getFeatureMapCount() {
      return internalGetFeatureMap().getMap().size();
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */
    @java.lang.Override
    public boolean containsFeatureMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetFeatureMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFeatureMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.tensorflow.example.FeatureConfiguration> getFeatureMap() {
      return getFeatureMapMap();
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, org.tensorflow.example.FeatureConfiguration> getFeatureMapMap() {
      return internalGetFeatureMap().getMap();
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
org.tensorflow.example.FeatureConfiguration getFeatureMapOrDefault(
        java.lang.String key,
        /* nullable */
org.tensorflow.example.FeatureConfiguration defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, org.tensorflow.example.FeatureConfiguration> map =
          internalGetFeatureMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */
    @java.lang.Override
    public org.tensorflow.example.FeatureConfiguration getFeatureMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, org.tensorflow.example.FeatureConfiguration> map =
          internalGetFeatureMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearFeatureMap() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableFeatureMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */
    public Builder removeFeatureMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableFeatureMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.tensorflow.example.FeatureConfiguration>
        getMutableFeatureMap() {
      bitField0_ |= 0x00000001;
      return internalGetMutableFeatureMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */
    public Builder putFeatureMap(
        java.lang.String key,
        org.tensorflow.example.FeatureConfiguration value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableFeatureMap().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */
    public Builder putAllFeatureMap(
        java.util.Map<java.lang.String, org.tensorflow.example.FeatureConfiguration> values) {
      internalGetMutableFeatureMap().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.ExampleParserConfiguration)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.ExampleParserConfiguration)
  private static final org.tensorflow.example.ExampleParserConfiguration DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.example.ExampleParserConfiguration();
  }

  public static org.tensorflow.example.ExampleParserConfiguration getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExampleParserConfiguration>
      PARSER = new com.google.protobuf.AbstractParser<ExampleParserConfiguration>() {
    @java.lang.Override
    public ExampleParserConfiguration parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExampleParserConfiguration> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExampleParserConfiguration> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.tensorflow.example.ExampleParserConfiguration getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

